### ISSUE TITLE
Инициализация DefaultUIState

### ISSUE THREAD

**Issue by pilat** [sergeysibara/react-ui-states#1]
Добрый день! В вашем коде в default-ui-state.js в конструкторе имеется вызов this._setStoreModels(), заключенный в setTimeout. Зачем это сделано? Подозреваю, что за счет этого довольно простой код у меня выводит пустоту при первой отрисовке:

``` javascript
const myProfileStore = Stores.myProfile;
const currentPageStore = Stores.currentPage;
export class TagsComponent extends BaseComponent {
    componentWillMount() {
        super.componentWillMount();
        this.uiState = new DefaultUIState(this, null, [{ store: currentPageStore }, { store: myProfileStore }]);
    }
    render() {
        var myProfileLink = this.uiState.get('myProfile.link');
        return <p>Ok: {myProfileLink}</p>
   }
}
```

Если я убираю этот setTimeout, то все работает нормально

**Comment by sergeysibara** [comment]
Добрый день!
Без setTimeout не будет работать пример "filters". 
При вызове _setStoreModels() вызовется getModel() из https://github.com/sergeysibara/react-ui-states/blob/master/src/stores/default-store-decorator.js в конце которого вызовется сallback convertModel, который соответствует методу applyFilter из https://github.com/sergeysibara/react-ui-states/blob/master/examples/filters/src/list.js. Ошибка будет из-за того, что this.uiState в компоненте еще не успеет получить значение, т.к. все еще будет выполняться конструктор DefaultUIState.

Для решения обоих проблем, в setTimeout после this._setStoreModels(), следовало бы вызывать обновление компонента - this._updateComponent().

**Comment by pilat** [comment]
Да, у меня проблема уходит, если в default-ui-state.js поставить:

``` javascript
setTimeout(()=> {
    this._setStoreModels();
    this._updateComponent();
}, 0);
```

**Comment by sergeysibara** [comment]
Спасибо, что сообщили о баге! 
Запушил изменения.
